server:
  port: 8088
  context-path: /cmfz
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: 123456
  #  mvc:
  #    view:
  #      prefix: /
  #      suffix: .jsp
  http:
    encoding:
      force: true
      charset: UTF-8
    multipart:
      max-file-size: 50MB
      max-request-size: 1024MB
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: com/baizhi/dao/*Mapper.xml